import assert from "node:assert/strict";import {randomUUID} from "node:crypto";import test from "node:test";import {neon} from "@neondatabase/serverless";
import {cancelSocialEvent,loadSocial,respondToSocialEvent,saveSocialAvailability,saveSocialEvent,saveSocialSettings} from "../lib/social-groups/service";
import {createTemplateInvite,changeTemplateMember,loadTemplateMembers} from "../lib/calendar-sharing/service";
import {redeemMemberInvitation} from "../lib/calendar-sharing/invitations";import {hashToken} from "../lib/security/tokens";import {normalizeInviteCode} from "../lib/security/invites";import type {TemplateSession} from "../lib/calendar-sharing/access";
const connection=process.env.SOCIAL_TEST_DATABASE_URL;
test("Social database authority, capacity and practical group workflows",{skip:!connection},async(t)=>{
 assert.equal(new URL(connection!).hostname,"ep-weathered-sea-a763290t-pooler.ap-southeast-2.aws.neon.tech");process.env.APP_DATABASE_URL=connection;const sql=neon(connection!);const calendarId=randomUUID(),foreignId=randomUUID();
 const make=(permission:"owner"|"editor"|"viewer",calendar=calendarId):TemplateSession=>({calendarId:calendar,membershipId:randomUUID(),userId:randomUUID(),calendarName:"Social qualification",calendarType:"social_groups",calendarTimezone:"Pacific/Auckland",permission,userName:"Qualification",userEmail:"test@example.invalid",participantId:null,displayName:null,colorKey:null,profileSlot:null});
 const owner=make("owner"),admin=make("editor"),member=make("editor"),other=make("editor"),viewer=make("viewer"),foreign=make("owner",foreignId);
 await sql.transaction([
 sql`INSERT INTO calendars(id,name,calendar_type,timezone) VALUES(${calendarId},'Social isolated qualification','social_groups','Pacific/Auckland'),(${foreignId},'Social foreign qualification','social_groups','Pacific/Auckland')`,
 ...[owner,admin,member,other,viewer,foreign].map(s=>sql`INSERT INTO calendar_memberships(id,calendar_id,user_id,permission) VALUES(${s.membershipId},${s.calendarId},${s.userId},${s.permission}::calendar_permission)`),
 sql`INSERT INTO template_member_roles(calendar_id,user_id,role) VALUES(${calendarId},${admin.userId},'admin')`
 ]);
 const date=new Date(Date.now()+7*86400000).toISOString().slice(0,10),month=date.slice(0,7);
 const event=(hour:number,capacity:number|null=null)=>({requestId:randomUUID(),title:"Group event",location:"Meeting place",notes:"Bring a book",start:`${date}T${String(hour).padStart(2,"0")}:00`,end:`${date}T${String(hour+2).padStart(2,"0")}:00`,capacity});
 const winner=(r:PromiseSettledResult<unknown>[])=>r.filter(v=>v.status==="fulfilled").length;
 await t.test("members create overlapping events without parenting approvals; viewers cannot write",async()=>{await saveSocialEvent(member,event(9));await saveSocialEvent(other,event(9));await assert.rejects(saveSocialEvent(viewer,event(10)));assert.equal((await loadSocial(member,month)).events.length,2);});
 await t.test("capacity concurrency has one winner and Maybe remains available",async()=>{const created=await saveSocialEvent(admin,event(11,1));assert.equal(winner(await Promise.allSettled([respondToSocialEvent(member,{eventId:created.id,response:"going"}),respondToSocialEvent(other,{eventId:created.id,response:"going"})])),1);await respondToSocialEvent(other,{eventId:created.id,response:"maybe"});await assert.rejects(respondToSocialEvent(viewer,{eventId:created.id,response:"maybe"}));await assert.rejects(respondToSocialEvent(foreign,{eventId:created.id,response:"going"}));});
 await t.test("overlapping Going is saved with a warning instead of blocked",async()=>{const one=await saveSocialEvent(admin,event(14)),two=await saveSocialEvent(admin,event(15));await respondToSocialEvent(member,{eventId:one.id,response:"going"});const response=await respondToSocialEvent(member,{eventId:two.id,response:"going"});assert.ok(response.warning?.includes("Your response is saved"));});
 await t.test("own edits, revisions, capacity changes and cancellations are bounded",async()=>{const data=event(17,1);const created=await saveSocialEvent(member,data);await respondToSocialEvent(member,{eventId:created.id,response:"going"});await assert.rejects(saveSocialEvent(other,{...data,id:created.id,version:1,title:"Not mine"}));const results=await Promise.allSettled([saveSocialEvent(member,{...data,id:created.id,version:1,title:"Changed"}),cancelSocialEvent(admin,{id:created.id,version:1})]);assert.equal(winner(results),1);const row=(await loadSocial(member,month)).events.find(e=>e.id===created.id)!;if(!row.cancelled)await cancelSocialEvent(member,{id:row.id,version:row.version});await assert.rejects(respondToSocialEvent(other,{eventId:created.id,response:"maybe"}));});
 await t.test("closed group creation policy respects owner/admin and existing own edits",async()=>{await saveSocialSettings(admin,false);await assert.rejects(saveSocialEvent(member,event(19)));await assert.rejects(saveSocialSettings(member,true));const own=await saveSocialEvent(owner,event(19));await saveSocialEvent(admin,{...event(19),id:own.id,version:1,title:"Organised"});assert.equal((await loadSocial(member,month)).canCreate,false);await saveSocialSettings(owner,true);});
 await t.test("duplicate create keys and personal availability stay deterministic",async()=>{const payload=event(7);assert.equal(winner(await Promise.allSettled([saveSocialEvent(member,payload),saveSocialEvent(member,payload)])),1);await saveSocialAvailability(member,{date,status:"available",note:"Evening works"});await saveSocialAvailability(member,{date,status:"unavailable",note:"Plans changed"});await saveSocialAvailability(other,{date,status:"available",note:""});const data=await loadSocial(member,month);assert.equal(data.availability.filter(a=>a.own).length,1);assert.equal(data.availability.find(a=>a.own)?.status,"unavailable");await assert.rejects(saveSocialAvailability(viewer,{date,status:"available",note:""}));});
 await t.test("group admins invite members but only owners appoint admins",async()=>{await assert.rejects(createTemplateInvite(admin,"admin",[]));await assert.rejects(createTemplateInvite(owner,"manager",[]));const invite=await createTemplateInvite(owner,"admin",[]),user=randomUUID();assert.equal(await redeemMemberInvitation(hashToken(normalizeInviteCode(invite.code)),user),calendarId);const members=await loadTemplateMembers(owner);assert.ok(members.members.some(m=>m.role==="admin"));const rows=await sql`SELECT id FROM calendar_memberships WHERE calendar_id=${calendarId} AND user_id=${user}`;await changeTemplateMember(owner,rows[0].id,"viewer");const scoped=await sql`SELECT permission,participant_id FROM calendar_memberships WHERE id=${rows[0].id}`;assert.equal(scoped[0].permission,"viewer");assert.equal(scoped[0].participant_id,null);});
});
