import { NextResponse,type NextRequest } from "next/server";
import { z } from "zod";
import { getCalendarSession } from "@/lib/security/session";
import { matchesExpectedCalendar } from "@/lib/calendar-sharing/policy";
import { isSameOriginMutation } from "@/lib/security/request";
import { socialAvailabilitySchema,socialCancelSchema,socialEventSchema,socialRsvpSchema,socialSettingsSchema } from "@/lib/social-groups/contracts";
import { cancelSocialEvent,loadSocial,respondToSocialEvent,saveSocialAvailability,saveSocialEvent,saveSocialSettings,SocialError } from "@/lib/social-groups/service";
function fail(error:unknown){if(error instanceof SocialError)return NextResponse.json({error:error.message},{status:error.status});const db=error as{constraint?:string;message?:string;cause?:{constraint?:string;message?:string}};const constraint=db.constraint??db.cause?.constraint??"";if(constraint.startsWith("social_"))return NextResponse.json({error:constraint.includes("request_key")?"This event was already submitted. Reload to see it.":db.cause?.message??db.message??"This change could not be saved. Reload and try again."},{status:409});return NextResponse.json({error:"The group request could not be completed. Please try again."},{status:500});}
export async function GET(request:NextRequest){const session=await getCalendarSession();if(!session)return NextResponse.json({error:"Calendar access is required."},{status:401});if(!matchesExpectedCalendar(request.headers.get("x-covie-calendar-id"),session.calendarId))return NextResponse.json({error:"Your selected calendar changed. Reload this page."},{status:409});try{return NextResponse.json(await loadSocial(session,request.nextUrl.searchParams.get("month")??undefined));}catch(error){return fail(error);}}
const input=z.discriminatedUnion("action",[z.object({action:z.literal("event"),data:socialEventSchema}),z.object({action:z.literal("cancel"),data:socialCancelSchema}),z.object({action:z.literal("rsvp"),data:socialRsvpSchema}),z.object({action:z.literal("availability"),data:socialAvailabilitySchema}),z.object({action:z.literal("settings"),data:socialSettingsSchema})]);
export async function POST(request:NextRequest){if(!isSameOriginMutation(request))return NextResponse.json({error:"This request was blocked for safety."},{status:403});const session=await getCalendarSession();if(!session)return NextResponse.json({error:"Calendar access is required."},{status:401});if (!matchesExpectedCalendar(request.headers.get("x-covie-calendar-id"), session.calendarId)) return NextResponse.json({ error: "Your selected calendar changed. Reload this page before saving." }, { status: 409 });
  const parsed=input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Check the event details."},{status:400});try{const value=parsed.data;switch(value.action){case"event":return NextResponse.json(await saveSocialEvent(session,value.data));case"cancel":return NextResponse.json(await cancelSocialEvent(session,value.data));case"rsvp":return NextResponse.json(await respondToSocialEvent(session,value.data));case"availability":return NextResponse.json(await saveSocialAvailability(session,value.data));case"settings":return NextResponse.json(await saveSocialSettings(session,value.data.membersCanCreate));}}catch(error){return fail(error);}}
